#define ZKCHECK_MAJOR 1
#define ZKCHECK_MINOR 0
#define ZKCHECK_DEVMINOR 0

#define STRINGIFY(x) STRING(x)
#define STRING(VER) #VER
#if ZKCHECK_MINOR == ZKCHECK_DEVMINOR
#define ZKCHECK_VERSION_STRING STRINGIFY(ZKCHECK_MAJOR) "." STRINGIFY(ZKCHECK_DEVMINOR)
#define ZKCHECK_VERSION ZKCHECK_MAJOR,ZKCHECK_MINOR,0,0
#else
#define ZKCHECK_VERSION_STRING STRINGIFY(ZKCHECK_MAJOR) "." STRINGIFY(ZKCHECK_DEVMINOR) " dev"
#define ZKCHECK_VERSION ZKCHECK_MAJOR,ZKCHECK_MINOR,99,0
#endif
#define LEGALCOPYRIGHT L"Copyright (C) 2016 709"
